//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapciRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alisveris
    {
        public int alisverisid { get; set; }
        public string kitap { get; set; }
        public string ogrenci { get; set; }
        public Nullable<System.DateTime> alistarihi { get; set; }
        public Nullable<System.DateTime> iadetarihi { get; set; }
        public string veren { get; set; }
    }
}
