//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapciRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelBilgiler
    {
        public int gbid { get; set; }
        public string okuladi { get; set; }
        public string mudur { get; set; }
        public string egitimyili { get; set; }
        public string sorumlu { get; set; }
        public Nullable<int> kitapgunsayisi { get; set; }
    }
}
