//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapciRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int kitapid { get; set; }
        public Nullable<int> barkod { get; set; }
        public string kitapadi { get; set; }
        public string yazar { get; set; }
        public string yayinevi { get; set; }
        public string turu { get; set; }
        public Nullable<System.DateTime> basimtarihi { get; set; }
        public string konum { get; set; }
        public string konumsira { get; set; }
        public string aciklama { get; set; }
        public string durum { get; set; }
        public string okunma { get; set; }
    }
}
