//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapciRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int kullaniciid { get; set; }
        public string adsoyad { get; set; }
        public string kullaniciadi { get; set; }
        public Nullable<int> sifre { get; set; }
        public string rol { get; set; }
    }
}
