//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitapciRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public int sinifid { get; set; }
        public string sinifadi { get; set; }
    }
}
